services:
  fix-permissions:
    image: alpine
    user: root
    command: sh -c "chown -R 10001:0 /var/opt/mssql/data /var/opt/mssql/log /var/opt/mssql/secrets && echo 'Permissions fixed'"
    volumes:
      - sqlserver_data:/var/opt/mssql/data
      - sqlserver_log:/var/opt/mssql/log
      - sqlserver_secrets:/var/opt/mssql/secrets

  sqlserver:
    container_name: ventafacil-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'VentaFacilDb123!'
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
      MSSQL_MEMORY_LIMIT_MB: 1024
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data
      - sqlserver_log:/var/opt/mssql/log
      - sqlserver_secrets:/var/opt/mssql/secrets
    networks:
      default:
        aliases:
          - sqlserver
          - ventafacil-db
    depends_on:
      fix-permissions:
        condition: service_completed_successfully
    restart: unless-stopped

  ventafacil.web:
    image: ventafacil.web
    build:
      context: .
      dockerfile: VentaFacil.web/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=ventafacil-db;Database=VentaFacilDB;User Id=sa;Password=VentaFacilDb123!;TrustServerCertificate=true;MultipleActiveResultSets=true;
      - ConnectionStrings__MasterConnection=Server=ventafacil-db;Database=master;User Id=sa;Password=VentaFacilDb123!;TrustServerCertificate=true;
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - ./dataprotection_keys:/app/keys
      - ./uploads:/wwwroot/uploads
      - /etc/letsencrypt/live/ventafacil-web.com:/certs:ro
      - ./init.sql:/app/init/init.sql
    restart: unless-stopped

volumes:
  sqlserver_data:
  sqlserver_log:
  sqlserver_secrets:


networks:
  default:
    driver: bridge
