services:
  sqlserver:
    container_name: ventafacil-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'VentaFacilDb123!'
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - "1455:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data
      - sqlserver_log:/var/opt/mssql/log
      - sqlserver_secrets:/var/opt/mssql/secrets
    networks:
      default:
        aliases:
          - sqlserver
    restart: unless-stopped

  ventafacil.web:
    image: ventafacil.web
    build:
      context: .
      dockerfile: VentaFacil.web/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=VentaFacilDB;User Id=sa;Password=VentaFacilDb123!;TrustServerCertificate=true;
      - ConnectionStrings__MasterConnection=Server=sqlserver,1433;Database=master;User Id=sa;Password=VentaFacilDb123!;TrustServerCertificate=true;
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
      # ASPNETCORE_URLS removido para usar la config de Kestrel en appsettings.json
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - ./dataprotection_keys:/app/keys
      - ./uploads:/wwwroot/uploads
      - /etc/letsencrypt/live/ventafacil-web.com:/certs:ro
    depends_on:
      - sqlserver
    restart: unless-stopped

  postfix:
    image: boky/postfix
    container_name: postfix
    environment:
      ALLOWED_SENDER_DOMAINS: "ventafacil-web.com"
      General_maillog_file: "/dev/stdout"
    # No exponemos el puerto 25 al host para evitar conflictos/seguridad, solo interno
    # ports:
    #   - "25:25" 
    networks:
      default:
        aliases:
          - mailserver
    restart: always

volumes:
  sqlserver_data:
  sqlserver_log:
  sqlserver_secrets:


networks:
  default:
    driver: bridge
